version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /vscode-ext
    schedule:
      interval: monthly
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
